name: codepath-test
channels:
  - pytorch
  - fastai
  - conda-forge
dependencies:
  - aiohttp=3.9.5=py310hd125d64_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h2aa6e3c_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd03087b_2
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.19=h5cf208e_1
  - aws-c-cal=0.6.12=h35c0bb2_0
  - aws-c-common=0.9.17=h03532ee_0
  - aws-c-compression=0.2.18=h35c0bb2_4
  - aws-c-event-stream=0.4.2=h7d5773a_10
  - aws-c-http=0.8.1=h00faecf_13
  - aws-c-io=0.14.8=h6dd71cf_0
  - aws-c-mqtt=0.10.4=h92d7a41_2
  - aws-c-s3=0.5.8=hef457b3_2
  - aws-c-sdkutils=0.1.16=h35c0bb2_0
  - aws-checksums=0.1.18=h35c0bb2_4
  - aws-crt-cpp=0.26.8=h77ed2c0_9
  - aws-sdk-cpp=1.11.267=h108e708_8
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py310h1253130_1
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.28.1=h93a5062_0
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hd1e100b_0
  - catalogue=2.0.10=py310hbe9552e_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310hdcd7c05_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpathlib=0.16.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - confection=0.1.4=py310ha73103e_0
  - contourpy=1.2.1=py310h21239e6_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cymem=2.0.8=py310h1253130_1
  - cython-blis=0.7.10=py310h280b8fa_2
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.19.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py310h692a8b6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=hebf3989_0
  - fastai=2.7.15=py_0
  - fastbook=0.0.28=py_0
  - fastcore=1.5.35=py_0
  - fastdownload=0.0.7=py_0
  - fastprogress=1.0.3=py_0
  - filelock=3.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310hd125d64_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.4.1=py310hd125d64_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gdk-pixbuf=2.42.11=h13c029f_0
  - gettext=0.22.5=h8fbad5d_2
  - gettext-tools=0.22.5=h8fbad5d_2
  - gflags=2.2.2=hc88da5d_1004
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.0=hc6770e3_0
  - gmp=6.3.0=hebf3989_1
  - gmpy2=2.1.5=py310he883d71_0
  - graphite2=1.3.13=hebf3989_1003
  - graphviz=9.0.0=h3face73_1
  - gtk2=2.24.33=h7895bb2_4
  - gts=0.7.6=he42f4ea_4
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=8.4.0=hbe0f7c0_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - huggingface_hub=0.23.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.24.0=pyh707e725_0
  - ipywidgets=8.1.2=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hbe9552e_3
  - jsonschema=4.22.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.22.0=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hbe9552e_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py310h38f39d4_1
  - krb5=1.21.2=h92f50d5_0
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20240116.2=cxx17_hebf3989_0
  - libarrow=16.0.0=h23f55cf_1_cpu
  - libarrow-acero=16.0.0=h00cdb27_1_cpu
  - libarrow-dataset=16.0.0=h00cdb27_1_cpu
  - libarrow-substrait=16.0.0=hc68f6b8_1_cpu
  - libasprintf=0.22.5=h8fbad5d_2
  - libasprintf-devel=0.22.5=h8fbad5d_2
  - libblas=3.9.0=22_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=22_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.7.1=h2d989ff_0
  - libcxx=17.0.6=h5f092b4_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgd=2.3.3=hfdf3952_9
  - libgettextpo=0.22.5=h8fbad5d_2
  - libgettextpo-devel=0.22.5=h8fbad5d_2
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libglib=2.80.2=h535f939_0
  - libgoogle-cloud=2.23.0=hbebe991_1
  - libgoogle-cloud-storage=2.23.0=h8a76758_1
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libintl=0.22.5=h8fbad5d_2
  - libintl-devel=0.22.5=h8fbad5d_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=22_osxarm64_openblas
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libparquet=16.0.0=hcf52c46_1_cpu
  - libpng=1.6.43=h091b4b1_0
  - libprotobuf=4.25.3=hbfab5d5_0
  - libre2-11=2023.09.01=h7b2c953_2
  - librsvg=2.58.0=hb3d354b_1
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.3=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.6.0=h07db509_3
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp=1.4.0=h54798ee_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.15=hf346824_0
  - libxml2=2.12.6=h0d0cfa8_2
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=18.1.5=hde57baf_0
  - lz4-c=1.9.4=hb7217d7_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310hd125d64_0
  - matplotlib=3.8.4=py310hb6292c7_0
  - matplotlib-base=3.8.4=py310h2439c42_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h41d338b_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py310h8e9501a_0
  - multiprocess=0.70.16=py310hd125d64_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.10=py310h1253130_1
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.4=hd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook=7.1.3=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py310hd45542a_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.0=h0d3ecfb_0
  - orc=2.0.0=h4aad248_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py310h401b61c_0
  - pandoc=3.1.13=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.52.2=hb067d4f_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathy=0.10.2=pyhd8ed1ab_0
  - pcre2=10.43=h26f9a81_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py310h81a8c2e_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=hebf3989_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - preshed=3.0.9=py310h1253130_1
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.8=py310hd125d64_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=16.0.0=py310h7ed268f_0
  - pyarrow-core=16.0.0=py310h75075a0_0_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.7.1=pyhd8ed1ab_0
  - pydantic-core=2.18.2=py310h8ffd6aa_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.2=py310hb3aa912_0
  - pyobjc-framework-cocoa=10.2=py310hb3aa912_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.12=h01493a6_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-graphviz=0.20.3=pyh717bed2_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py310h2aa6e3c_0
  - python_abi=3.10=4_cp310
  - pytorch=2.2.2=py3.10_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2aa6e3c_1
  - pyzmq=26.0.3=py310h16e08c9_0
  - qtconsole-base=5.5.2=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - regex=2024.5.10=py310ha6dd24b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.18.1=py310h947b723_0
  - safetensors=0.4.3=py310hd442715_0
  - scikit-learn=1.4.2=py310h7ef31dd_0
  - scipy=1.13.0=py310h7057308_1
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - snappy=1.2.0=hd04f947_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spacy=3.7.3=py310h1359cc7_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - srsly=2.4.8=py310h1253130_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - terminado=0.18.1=pyh31c8845_0
  - thinc=8.2.2=py310h1359cc7_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tokenizers=0.19.1=py310hb145503_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.2.2=py310_cpu
  - torchvision=0.17.2=py310_cpu
  - tornado=6.4=py310hd125d64_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - transformers=4.40.2=pyhd8ed1ab_0
  - typer=0.9.4=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py310h2aa6e3c_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wasabi=1.1.2=py310hbe9552e_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - weasel=0.3.4=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xxhash=0.8.2=hb547adb_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py310hd125d64_0
  - zeromq=4.3.5=h5119023_3
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.6=hb46c0d2_0
